spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/template?currentSchema=template_schema
    username: postgres
    password: 123456

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG

redis:
  singleAddress: redis://localhost:6379